language: scala
jdk:
    - openjdk7
    - oraclejdk7
scala:
   - 2.11.6
services:
    - redis-server
notifications:
  email:
    - jeffhann@gmail.com 
before_install:
  - sudo ./generate_keys.sh
script: "sbt clean coverage test"
after_success: "sbt coveralls"
